# Generated by Django 2.2.7 on 2019-11-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='product_type',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
            preserve_default=False,
        ),
    ]
