# Generated by Django 2.1.2 on 2019-11-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_backgroundimage_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimage',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='coverphoto',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cropping',
        ),
    ]
