# Generated by Django 2.1.2 on 2020-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_client_secret',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
