# Generated by Django 2.1.2 on 2021-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shippingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('code', models.CharField(max_length=300)),
            ],
        ),
    ]
