# Generated by Django 2.1.2 on 2020-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret_token',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
