# Generated by Django 2.1.2 on 2021-03-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='carts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
