# Generated by Django 2.1.2 on 2020-03-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_secret_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='last_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
