# Generated by Django 2.1.2 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210313_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='minimum_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
