# Generated by Django 2.1.2 on 2021-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupons_minimum_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
