# Generated by Django 2.2.12 on 2020-04-03 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user', models.BooleanField(default=False)),
                ('use_saved_shipping', models.BooleanField(default=False)),
                ('favourite_products', models.ManyToManyField(blank=True, to='products.Product')),
                ('saved_shipping', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShippingDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
