# Generated by Django 2.1.2 on 2019-12-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_shipping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShippingDetails'),
        ),
    ]
