# Generated by Django 2.1.2 on 2020-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('users', '0002_auto_20200430_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_orders',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_orders',
            field=models.ManyToManyField(blank=True, to='cart.Order'),
        ),
    ]
